###create provider and pig
POST http://localhost:4000/api/tasks/task/provider
content-type: application/json

{
  "name": "provider3",
  "phone": "12589",
  "address": "calle 1",
  "id_task": "ba399aca-0817-4358-8c5e-1b8c31c92fc2",
  "animal": {
    "price": 100,
    "weight": 100,
    "status": "isLive"
  }
}




###
POST http://localhost:4000/api/providers/storage/856f8f9a-ab03-422e-ac38-2099dc70940d
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="photo"; filename="cope.png"

< /Users/macbook/Documents/api-pig/src/img/cope.png
--WebAppBoundary--

###
### create task
POST https://localhost:4000/api/task
content-type: application/json

{
    "task_name": "task  44",
    "task_description": "la concordi"
}







### Delete task
DELETE http://localhost:4000/api/tasks/task/2741d718-9ee9-11ee-96d9-0242ac150002
### obtener tareas con sus proveedores y cerdos
GET http://localhost:4000/api/task

### obtener tareas con sus proveedores y cerdos
GET https://apig.luitam.com/api/providers
